# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the IPU drivers
#
obj-$(CONFIG_IPU_BRIDGE) += ipu-bridge.o
obj-$(CONFIG_VIDEO_INTEL_IPU_COMMON)	+= ipu/
obj-y	+= ipu3/
obj-y	+= ivsc/
obj-$(CONFIG_VIDEO_INTEL_IPU6)	+= ipu6/
obj-$(CONFIG_VIDEO_INTEL_IPU7)	+= ipu7/
