# SPDX-License-Identifier: GPL-2.0-only
intel-ipu-common-y := ipu-bus.o

obj-$(CONFIG_VIDEO_INTEL_IPU_COMMON)	+= intel-ipu-common.o

intel-ipu-isys-y := \
	ipu-isys-subdev.o \
	ipu-isys-queue.o

obj-$(CONFIG_VIDEO_INTEL_IPU_ISYS)	+= intel-ipu-isys.o

